name: pymast
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - numpy>=1.20
  - pandas>=1.3
  - matplotlib>=3.4
  - statsmodels>=0.12
  - networkx>=2.5
  - scipy>=1.7.1
  - scikit-learn>=0.24
  - h5py>=3.0
  - numba>=0.53
  - dask>=2021.3.0
  - dask-ml>=1.9.0
  - distributed>=2021.3.0
  - pytables>=3.8.0
  - intervaltree>=3.1.0
